language: ruby

rvm:
- 1.9.3
- 2.0.0
- 2.1.3

before_install:
- sudo apt-get update
- sudo apt-get install -y ruby-dev make pkg-config libxml2-dev libxslt-dev libcurl3

install: NOKOGIRI_USE_SYSTEM_LIBRARIES=1 bundle install

script: 'bundle exec thor spec && bundle exec thor fixture:local'
